// packages/angular/src/index.component.ts
import { Component, Input } from "@angular/core";

import * as common from "relative-time-component";

import { indexTemplateHtml } from "./variables";

/**
 * @public
 */
@Component({
    selector: "relative-time",
    template: indexTemplateHtml,
})
export class RelativeTimeComponent {
    @Input()
    time: Date | number;
    @Input()
    locale: common.Locale | null;

    title = "";
    private relativeTime = "";
    private timer: NodeJS.Timer;
    private isHovering = false;

    get timeText() {
        return this.isHovering ? this.title : this.relativeTime;
    }

    ngOnInit() {
        this.relativeTime = common.getRelativeTime(this.time, this.locale);
        this.title = common.format(this.time);
        this.timer = setInterval(() => {
            this.relativeTime = common.getRelativeTime(this.time, this.locale);
        }, 60 * 1000);
    }

    ngOnDestroy() {
        if (this.timer) {
            clearInterval(this.timer);
        }
    }

    mouseenter() {
        this.isHovering = true;
    }

    mouseleave() {
        this.isHovering = false;
    }
}

// packages/react-native/src/index.tsx
import React from 'react'
import { Text } from 'react-native'
import * as common from 'relative-time-component'
export * from 'relative-time-component'

/**
 * @public
 */
export class RelativeTime extends React.PureComponent<{
  time: Date | number;
  locale?: common.Locale | null;
}, {}> {
  public state = {
    relativeTime: '',
    title: '',
    isHovering: false
  }
  private timer!: NodeJS.Timer

  private get timeText() {
    return this.state.isHovering ? this.state.title : this.state.relativeTime
  }

  UNSAFE_componentWillMount() {
    let relativeTime = common.getRelativeTime(this.props.time, this.props.locale)
    const title = common.format(this.props.time)
    this.setState({ relativeTime, title })
    this.timer = setInterval(() => {
      relativeTime = common.getRelativeTime(this.props.time, this.props.locale)
      this.setState({ relativeTime })
    }, 60 * 1000)
  }

  componentWillUnmount() {
    if (this.timer) {
      clearInterval(this.timer)
    }
  }

  render() {
    return (
      <Text onPress={() => this.onPress()}>{this.timeText}</Text>
    )
  }

  private onPress() {
    this.setState({ isHovering: !this.state.isHovering })
  }
}
